cartage/urls.py
from django.urls import path

from . import views


app_name = 'cartage'
urlpatterns = [
  path('', views.index, name='home'),
  path('login/', views.login, name='login'),
  path('register/', views.register, name='register'),
  path('trips/', views.trips, name='trips'),
  path('profile/', views.profile, name='profile'),
  path('search/', views.search, name='search'),
  path('logResult/', views.landingL, name='landingL'),
  path('registerResult/', views.landingR, name='landingR' ),
  path('messages/', views.messages, name='messages'),
  path('help/', views.help, name='help')
 ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cartage/', include('cartage.urls'))
]

cartage/models.py
from django.db import models
from django.utils import timezone


class Address(models.Model):
    street = models.CharField(max_length=60)
    zip_code = models.IntegerField()
    city = models.CharField(max_length=40)

    def __str__(self):
        return ' '.join([self.street, str(self.zip_code), self.city])


class User(models.Model):
    firstname = models.CharField(max_length=25)
    lastname = models.CharField(max_length=25)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    email = models.EmailField()
    password = models.CharField(max_length=20)
    tel = models.IntegerField()
    car = models.BooleanField()
    rating = models.FloatField()
    total_votes = models.IntegerField()
    hours = models.IntegerField()

    def __str__(self):
        return self.email


class Trip(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name="student_user", null=True)
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, related_name="teacher_user", null=True)
    start = models.ForeignKey(Address, on_delete=models.CASCADE, related_name='start_address')
    stop = models.ForeignKey(Address, on_delete=models.CASCADE, related_name='stop_address')
    departure = models.DateTimeField()

    def has_passed(self):
        return self.departure > timezone.now()


class Message(models.Model):
    content = models.CharField(max_length=500)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    date = models.DateTimeField()



class Contact(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner')
    contact = models.ForeignKey(User, on_delete=models.CASCADE, related_name='contact')

cartage/views.py
from django.shortcuts import render, get_object_or_404

from django.db.models import Q
# Create your views here.
from django.utils import timezone

from cartage.models import User, Address, Trip, Contact, Message


def index(request):
    try:
        user = User.objects.filter(pk=request.session['user_id'])
    except(KeyError):
        return render(request, 'cartage/index.html')
    return render(request, 'cartage/index.html', {'user' : user})


def login(request):
    return render(request, 'cartage/login.html')


def landingL(request):
    user = get_object_or_404(User, pk=User.objects.get(email=request.POST['email']).id)
    if user.password == request.POST['password']:
        request.session['user_id'] = user.id
        return render(request, 'cartage/index.html', {'type': "Connexion réussie !", 'user': user})
    else:
        return render(request, 'cartage/login.html')


def landingR(request):
    if User.objects.filter(email=request.POST['email'], tel=request.POST['tel']).count() == 0:
        st = " ".join(request.POST['street'].split())
        zi = " ".join(request.POST['zip_code'].split())
        ci = " ".join(request.POST['city'].split())
        if Address.objects.filter(street=st, zip_code=zi, city=ci).count() == 0:
            a = Address(street=st,
                        zip_code=zi,
                        city=ci)
            a.save()
        else:
            a = Address.objects.get(street=st, zip_code=zi, city=ci)
        user = User(
            firstname=request.POST['firstname'],
            lastname=request.POST['lastname'],
            address=a,
            email=request.POST['email'],
            password=request.POST['password'],
            tel=request.POST['tel'],
            car=request.POST['car'],
            rating=0,
            total_votes=0,
            hours=request.POST['hours']
        )
        user.save()
        request.session['user_id'] = user.id
        return render(request, 'cartage/index.html', {'type': "Inscription réussie !", 'user': user})
    else:
        return render(request, 'cartage/register.html')


def register(request):
    return render(request, 'cartage/register.html')


def trips(request):
    if request.POST:
        user1 = User.objects.get(pk=request.session['user_id']) if request.POST['madeByTeacher'] else None
        user2 = None if request.POST['madeByTeacher'] else User.objects.get(pk=request.session['user_id'])
        start_st = " ".join(request.POST['start_street'].split())
        start_zi = " ".join(request.POST['start_zip'].split())
        start_ci = " ".join(request.POST['start_city'].split())

        stop_st = " ".join(request.POST['stop_street'].split())
        stop_zi = " ".join(request.POST['stop_zip'].split())
        stop_ci = " ".join(request.POST['stop_city'].split())

        if Address.objects.filter(street=start_st, zip_code=start_zi, city=start_ci).count() == 0:
            start_ad = Address(street=start_st,
                               zip_code=start_zi,
                               city=start_ci)
            start_ad.save()
        else:
            start_ad = Address.objects.get(street=start_st, zip_code=start_zi, city=start_ci)

        if Address.objects.filter(street=stop_st, zip_code=stop_zi, city=stop_ci).count() == 0:
            stop_ad = Address(street=stop_st,
                              zip_code=stop_zi,
                              city=stop_ci)
            stop_ad.save()
        else:
            stop_ad = Address.objects.get(street=stop_st, zip_code=stop_zi, city=stop_ci)

        trip = Trip(
            student=user2,
            teacher=user1,
            start=start_ad,
            stop=stop_ad,
            departure=request.POST['departure']
        )
        trip.save()
    user = User.objects.get(pk=request.session['user_id'])
    user_trips = Trip.objects.filter(Q(teacher_id=user.id) | Q(student_id=user.id))
    return render(request, 'cartage/trips.html', {'trips':user_trips, 'user' : user})


def profile(request):
    user = User.objects.get(pk=request.session['user_id'])
    if request.POST:
        for key in request.POST.keys():
            if key == 'firstname':
                user.firstname = request.POST['firstname']
            elif key == 'lastname':
                user.lastname = request.POST['lastname']
            elif key == 'street':
                st = " ".join(request.POST['street'].split())
                zi = " ".join(request.POST['zip_code'].split())
                ci = " ".join(request.POST['city'].split())
                if Address.objects.filter(street=st, zip_code=zi, city=ci).count() == 0:
                    a = Address(street=st,
                                zip_code=zi,
                                city=ci)
                    a.save()
                else:
                    a = Address.objects.get(street=st, zip_code=zi, city=ci)
                user.address = a
            elif key == 'email':
                if User.objects.filter(email=request.POST['email']).count() == 0:
                    user.email = request.POST['email']
            elif key == 'password':
                if user.password == request.POST['current_password']:
                    user.password = request.POST['password']
            elif key == 'tel':
                if User.objects.filter(tel=request.POST['tel']).count() == 0:
                    user.tel = request.POST['tel']
            elif key == 'car':
                user.car = request.POST['car']
            elif key == 'hours':
                user.hours = request.POST['hours']

        user.save()
    return render(request, 'cartage/profile.html', {'user' : user})


def search(request):
    user = User.objects.get(pk=request.session['user_id'])
    matches = User.objects.filter(car=not user.car)
    return render(request, 'cartage/search.html', { 'matches' : matches})


def messages(request):
    user = User.objects.get(pk=request.session['user_id'])
    if request.POST:
        for key in request.POST.keys():
            if key == 'match':
                if Contact.objects.filter(Q(owner=user, contact = User.objects.get(pk=request.POST['match'])) | Q(owner=User.objects.get(pk=request.POST['match']), contact = user)).count() == 0:
                    contact = Contact(
                        owner=user,
                        contact=User.objects.get(pk=request.POST['match'])
                    )
                    contact.save()
            if key == 'message':
                message = Message(
                    content=request.POST['message'],
                    sender=user,
                    date=timezone.now(),
                    receiver=User.objects.get(pk=request.POST['target'])
                )
                message.save()
    try:
        contacts = Contact.objects.filter(Q(owner=user) | Q(contact=user))
        users_and_messages= []
        for contact in contacts:
            subtab = []

            if contact.owner == user:
                subtab.append(contact.contact)
                if Message.objects.filter(Q(sender=user.id, receiver=contact.contact) | Q(receiver=user.id, sender=contact.contact)).count != 0:
                    subtab.append(Message.objects
                                  .filter(Q(sender=user, receiver=contact.contact) | Q(sender=contact.contact, receiver=user))
                                  .values('content', 'date', 'sender').order_by('date'))
                else:
                    subtab.append([])
            else:
                subtab.append(contact.owner)
                if Message.objects.filter(Q(sender=user.id, receiver=contact.owner) | Q(receiver=user.id, sender=contact.owner)).count != 0:
                    subtab.append(Message.objects
                                  .filter(Q(sender=user, receiver=contact.owner) | Q(sender=contact.owner, receiver=user))
                                  .values('content', 'date', 'sender').order_by('date'))
                else:
                    subtab.append([])
            users_and_messages.append(subtab)

    except(KeyError, Contact.DoesNotExist):
        return render(request, "cartage/search.html")
    finally:
        return render(request,
                      "cartage/messages.html",
                      {'users_and_messages' : users_and_messages,
                       'user' : user,
                       })


def help(request):
    return render(request, 'cartage/help.html')

cartage/templates/cartage/help.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'style.css'%}">
</head>

<body>
    <div class="banner">
    <nav id="container">
        <a href="{% url 'cartage:home' %}" class="home up"></a>
        <a href="{% url 'cartage:search' %}" class="findUser up"></a>
        <a href="{% url 'cartage:trips'%}" class="trips up"></a>
        <a href="{% url 'cartage:messages' %}" class="messages up"></a>
        <a href="{% url 'cartage:help' %}" class="help upTargeted"></a>
        <a href="{% url 'cartage:profile' %}" class="account up"></a>

        <a href="{% url 'cartage:home' %}" class="linknav"></a>
        <a href="{% url 'cartage:search' %}" class="linknav">Trouver un binôme</a>
        <a href="{% url 'cartage:trips'%}" class="linknav">Mes Trajets</a>
        <a href="{% url 'cartage:messages' %}" class="linknav">Messagerie</a>
        <a href="{% url 'cartage:help' %}" class="linknavTargeted">Aide</a>
        <a href="{% url 'cartage:profile' %}" class="linknav">Mon Profil</a>
    </nav>
</div>

    <div class="helpDiv">
    <h1>Les réponses à vos questions :</h1>
    <ul>
        <li>Qui sommes-nous</li>
        <p>Nous sommes de jeunes entrepreneurs motivés et altruistes, qui avons enfin trouvé un moyen d'aider notre
            prochain tout en exploitant nos compétences.</p>
            <br>

        <li>Pourquoi Cartage ?</li>
        <p>L'application Cartage est née du désir de jeunes entrepreneurs de mettre leurs ressources et leur motivation
            au service du plus grand nombre, en proposant un service innovant, puissant et fonctionnel. Leur but :
            permettre à tous ceux qui ont du mal à trouver un accompagnateur pour effectuer la conduite accompagnée
            de pouvoir le faire dans un cadre sécurisé, simple et bienveillant.</p>
            <br>

        <li>Accessibilité et valeurs :</li>
        <p>Nous sommes fiers de proposer notre application à toutes les personnes présentant un handicap, quel qu'il soit.
            L'inclusivité est une de nos priorités majeures, et nous travaillons en permanence avec des personnes issues
            de minorités.</p>
            <br>

        <li>Pourquoi un service payant ?</li>
        <p>Nous avons œuvré au maximum pour proposer un service gratuit, car notre priorité était d'aider un maximum
            de personnes. Malheureusement, le coût des serveurs et la réalité du marché nous ont rattrapé. C'est pourquoi
            nous prenons une commission modique de 20% sur toutes les transactions effectuées sur notre application.</p>
            <br>

        <li>Un problème lié à un conducteur ?</li>
        <p>N'hésitez pas à utiliser notre système d'évaluation afin de déconseiller ce conducteur à la communauté.
            Vous rendrez ainsi service à tout le monde en améliorant la qualité du service dans son ensemble.
            Bravo à vous !
        </p>
        <br>

        <li>Les Cartage Fidelity Points®</li>
        <p>En utilisant notre service vous pourrez bientôt cumuler des points de fidélité afin d'avoir accès
            à des récompenses réservées à nos utilisateurs les plus dévoués.
        </p>

    </ul>
        </div>

</body>

</html>

cartage/templates/cartage/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Bienvenue sur Cartage !</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

  {% if type %}
        <h1>{{type}} Bienvenue {{user.firstname}}</h1>
  {% endif %}
  {% if user.is_anonymous %}
  <form method="GET" action="{% url 'cartage:login' %}">
        <button class="transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300 bg-violet-500 rounded-full px-4 py-1 text-sm font-semibold text-white
        hover:bg-violet-400 active:bg-violet-700
        focus:outline-none focus:ring focus:ring-violet-300 "
        action="{% url 'cartage:login'%}" type="submit">Se connecter</button>
      </form>
    <form method="GET" action="{% url 'cartage:register' %}">
        <button class="transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300 bg-blue-500 rounded-full px-6 py-0.5 text-s font-semibold text-white
        hover:bg-blue-400 active:bg-blue-700
        focus:outline-none focus:ring focus:ring-blue-300"
        type="submit">S'inscrire</button>
        </form>
  {% else %}


<div class="banner">
    <nav id="container">
        <a href="{% url 'cartage:home' %}" class="home up"></a>
        <a href="{% url 'cartage:search' %}" class="findUser upTargeted"></a>
        <a href="{% url 'cartage:trips'%}" class="trips up"></a>
        <a href="{% url 'cartage:messages' %}" class="messages up"></a>
        <a href="{% url 'cartage:help' %}" class="help up"></a>
        <a href="{% url 'cartage:profile' %}" class="account up"></a>

        <a href="{% url 'cartage:home' %}" class="linknav"></a>
        <a href="{% url 'cartage:search' %}" class="linknavTargeted">Trouver un binôme</a>
        <a href="{% url 'cartage:trips'%}" class="linknav">Mes Trajets</a>
        <a href="{% url 'cartage:messages' %}" class="linknav">Messagerie</a>
        <a href="{% url 'cartage:help' %}" class="linknav">Aide</a>
        <a href="{% url 'cartage:profile' %}" class="linknav">Mon Profil</a>
    </nav>
</div>
  {% endif %}


</body>
</html>

cartage/templates/cartage/messages.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Ma messagerie - Cartage</title>
    <style>
        .sent
        {
           color:red;
        }
        .received
        {
           color:blue;
        }
        .d
        {
            font-style:italic
        }

    </style>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'style.css'%}">
</head>
<body>
    <div class="banner">
    <nav id="container">
        <a href="{% url 'cartage:home' %}" class="home up"></a>
        <a href="{% url 'cartage:search' %}" class="findUser up"></a>
        <a href="{% url 'cartage:trips'%}" class="trips up"></a>
        <a href="{% url 'cartage:messages' %}" class="messages upTargeted"></a>
        <a href="{% url 'cartage:help' %}" class="help up"></a>
        <a href="{% url 'cartage:profile' %}" class="account up"></a>

        <a href="{% url 'cartage:home' %}" class="linknav"></a>
        <a href="{% url 'cartage:search' %}" class="linknav">Trouver un binôme</a>
        <a href="{% url 'cartage:trips'%}" class="linknav">Mes Trajets</a>
        <a href="{% url 'cartage:messages' %}" class="linknavTargeted">Messagerie</a>
        <a href="{% url 'cartage:help' %}" class="linknav">Aide</a>
        <a href="{% url 'cartage:profile' %}" class="linknav">Mon Profil</a>
    </nav>
</div>
    <h1>Messagerie</h1>

        {% for contact, messages in users_and_messages %}
            {{contact.firstname}} {{contact.lastname}}
            {% for message in messages %}
                {% if message.sender == user.id %}

                    <p class="sent d">On {{message.date}}, {{contact.firstname}} sent:</p>
                    <p class="sent">{{message.content}}</p>
                {% elif message.sender == contact.id %}
                    <p class="received d">On {{message.date}}:</p>
                    <p class="received">{{message.content}}</p>
                {% else %}
                    <p> This is not good </p>
                {% endif %}
            {% empty %}
                <p>Dites coucou !</p>
            {% endfor %}
            <form action="{% url 'cartage:messages' %}" method="POST"> {% csrf_token %}
                <fieldset class="border-2 rounded shadow-sm border-slate-400 formulaire bg-slate-100">
                <label for="message{{contact.id}}"></label>
                <input type="text" name="message" class="placeholder:italic placeholder:text-slate-400 mt-1 border border-slate-400 rounded-md text-sm shadow-sm placeholder-slate-400
                focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" placeholder="Ecrivez votre message" id="message{{contact.id}}">
                <input type="checkbox" style="display:none;" name="target" id="target{{contact.id}}" value="{{contact.id}}" checked>
                <button type="submit" class="mt-4 ml-8 bg-sky-400 rounded-full px-4 py-1 text-s font-semibold text-white
                hover:bg-blue-400 active:bg-blue-700
                focus:outline-none focus:ring focus:ring-blue-300">Envoyer un message à {{contact.firstname}}</button>
                </fieldset>
            </form>
            <br> <br>
        {%endfor%}


</body>
</html>

cartage/templates/cartage/search.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<div class="banner">
    <nav id="container">
        <a href="{% url 'cartage:home' %}" class="home up"></a>
        <a href="{% url 'cartage:search' %}" class="findUser upTargeted"></a>
        <a href="{% url 'cartage:trips'%}" class="trips up"></a>
        <a href="{% url 'cartage:messages' %}" class="messages up"></a>
        <a href="{% url 'cartage:help' %}" class="help up"></a>
        <a href="{% url 'cartage:profile' %}" class="account up"></a>

        <a href="{% url 'cartage:home' %}" class="linknav"></a>
        <a href="{% url 'cartage:search' %}" class="linknavTargeted">Trouver un binôme</a>
        <a href="{% url 'cartage:trips'%}" class="linknav">Mes Trajets</a>
        <a href="{% url 'cartage:messages' %}" class="linknav">Messagerie</a>
        <a href="{% url 'cartage:help' %}" class="linknav">Aide</a>
        <a href="{% url 'cartage:profile' %}" class="linknav">Mon Profil</a>
    </nav>
</div>
<!--- match list with hidden form to add to contacts  --->
<h1 class="text-xl">Suggestions de binôme :</h1>
{%for match in matches%}
<div>
    <h2>{{match.firstname}} {{match.lastname}}</h2>
    <h3> {{match.address}} </h3>
    <h3>{%if match.car%} Voiture disponible {% else %} Pas de voiture {% endif %}</h3>
    <form action="{% url 'cartage:messages' %}" method="POST">
        {% csrf_token %}
        <input type="checkbox" style="display: none;" name="match" id="match{{match.id}}" value="{{match.id}}" checked>
        <button type="submit" class="bg-blue-200 rounded-full px-4 py-1 text-sm font-semibold text-slate-700
        hover:bg-blue-100 active:bg-blue-500
        focus:outline-none focus:ring focus:ring-blue-400"><img src="{% static 'content/message.svg'%}" class="w-5">Contacter</button>
    </form>
</div>
{% endfor %}
</body>
</html>

cartage/templates/cartage/trips.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mes voyages</title>
    <style>
        table, tr, td, th {
         border: 1px solid black;
        }
    </style>
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <script src="{% static 'js/trip.js'%}" defer></script>
</head>
<body>

    <div class="banner">
    <nav id="container">
        <a href="{% url 'cartage:home' %}" class="home up"></a>
        <a href="{% url 'cartage:search' %}" class="findUser up"></a>
        <a href="{% url 'cartage:trips'%}" class="trips upTargeted"></a>
        <a href="{% url 'cartage:messages' %}" class="messages up"></a>
        <a href="{% url 'cartage:help' %}" class="help up"></a>
        <a href="{% url 'cartage:profile' %}" class="account up"></a>

        <a href="{% url 'cartage:home' %}" class="linknav"></a>
        <a href="{% url 'cartage:search' %}" class="linknav">Trouver un binôme</a>
        <a href="{% url 'cartage:trips'%}" class="linknavTargeted">Mes Trajets</a>
        <a href="{% url 'cartage:messages' %}" class="linknav">Messagerie</a>
        <a href="{% url 'cartage:help' %}" class="linknav">Aide</a>
        <a href="{% url 'cartage:profile' %}" class="linknav">Mon Profil</a>
    </nav>
</div>
    {% if trips %}
    <table>
        <tr class="even:bg-white odd:bg-slate-200">
            <th>Départ</th>
            <th>Arrivée</th>
            <th>Date</th>
            <th>Binôme</th>
        </tr>
        {% for trip in trips %}
        <tr >
            <th>{{ trip.start }}</th>
            <th>{{ trip.stop }}</th>
            <th>{{ trip.departure }}</th>
            <th>{% if trip.student.id == user.id and trip.teacher.id != None%} {{trip.teacher.firstname}}
                {% elif trip.student.id != None %} {{trip.student.firstname}}
                {% else %} X {% endif %}</th>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
    <br> <br>
    <button class="bg-yellow-500 rounded-full px-4 py-1 text-sm font-semibold text-slate
    hover:bg-yellow-400 active:bg-yellow-700
    focus:outline-none focus:ring focus:ring-yellow-300" id="addTrip"><img src="{% static 'content/plussign.png' %}" alt="plus sign" id="plus_sign"><p>Ajouter un trajet: </p></button>
        <form action="{% url 'cartage:trips' %}" method="POST" id="formTrip"> {%csrf_token%}
            <label for="start">Départ</label>
            <fieldset id="start">
                <label for="start_street">Rue</label>
                <input type="text" id="start_street" name="start_street" class="placeholder:italic placeholder:text-slate-400 mt-1 border border-slate-400 rounded-md text-sm shadow-sm placeholder-slate-400
        focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" placeholder="Rue"> <br>
                <label for="start_zip">Code Postal</label>
                <input type="number" id="start_zip" name="start_zip" class="placeholder:italic placeholder:text-slate-400 mt-1 border border-slate-400 rounded-md text-sm shadow-sm placeholder-slate-400
        focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" placeholder="Code Postal"> <br>
                <label for="start_city">Ville</label>
                <input type="text" id="start_city" name="start_city" class="placeholder:italic placeholder:text-slate-400 mt-1 border border-slate-400 rounded-md text-sm shadow-sm placeholder-slate-400
        focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" placeholder="Ville"> <br>
            </fieldset>
            <label for="stop">Arrivée</label>
            <fieldset id="stop">
                <label for="stop_street">Rue</label>
                <input type="text" id="stop_street" name="stop_street" class="placeholder:italic placeholder:text-slate-400 mt-1 border border-slate-400 rounded-md text-sm shadow-sm placeholder-slate-400
        focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" placeholder="Rue"> <br>
                <label for="stop_zip">Code Postal</label>
                <input type="number" id="stop_zip" name="stop_zip" class="placeholder:italic placeholder:text-slate-400 mt-1 border border-slate-400 rounded-md text-sm shadow-sm placeholder-slate-400
        focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" placeholder="Code Postal"> <br>
                <label for="stop_city">Ville</label>
                <input type="text" id="stop_city" name="stop_city" class="placeholder:italic placeholder:text-slate-400 mt-1 border border-slate-400 rounded-md text-sm shadow-sm placeholder-slate-400
        focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" placeholder="Ville"> <br>
            </fieldset>
                <label for="madeByTeacher">Je suis accompagnateur</label>
                <input type="radio" name="madeByTeacher" id="madeByTeacher" value="1" class=" mt-1 border border-slate-400 rounded-md text-sm shadow-sm
        focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500">
                <label for="madeByStudent">Je suis accompagné</label>
                <input type="radio" name="madeByTeacher" id="madeByStudent" value="0" checked class=" mt-1 border border-slate-400 rounded-md text-sm shadow-sm
        focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500"> <br>
                <label for="departure">Date de départ</label>
                <input type="datetime-local" id="departure" name="departure" class=" mt-1 border border-slate-400 rounded-md text-sm shadow-sm
        focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500"> <br>
            <button type="submit" class="bg-blue-500 rounded-full px-4 py-1 text-sm font-semibold text-white
            hover:bg-blue-400 active:bg-blue-700
            focus:outline-none focus:ring focus:ring-blue-300 " id="buttonTrip">Sauvegarder</button>
        </form>



</body>
</html>